version: '3.1'

services:
  enetspace-client:
    image: edamh158/enetspace-client:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    stdin_open: true

  nginx:
    image: edamh158/enetspace-nginx:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - '80:80'
    depends_on:
      - enetspace-client

  enetspace-api:
    image: edamh158/enetspace-api:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - '8090:8080'
    environment:
      MONGODB_URI: mongodb://mongo:enetspace1@mongodb:27017/
      MONGODB_DB_NAME: enetspace-api-prod
      JWT_SECRET: edam1234
      JWT_EXPIRE: 30d
      SMTP_USERNAME: supchat24@outlook.com
      SMTP_PASSWORD: cin11149398
      NODE_ENV: development
      GOOGLE_CLIENT_ID: smth.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: SMTH-SMTH
      CLIENT_URL: http://enetspace-client:3000
      API_URL: http://localhost:8080/api/v1
    command: node dist/index.js

  mongodb:
    image: mongo:4.4.17-focal
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: enetspace1
      MONGO_URI: mongodb://mongo:enetspace1@localhost:27017/
    volumes:
      - db_prod:/data/db

volumes:
  db_prod:
