version: '3.1'

services:
  jenkins:
    build: . # Build the Dockerfile in the current directory (ops)
    container_name: jenkins # Optional: keep the name consistent
    ports:
      - '8000:8080'
      - '50000:50000'
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ops_overlay_network
      - default

  prometheus:
    image: prom/prometheus:v2.20.1
    volumes:
      - prometheus_data:/prometheus
      - ./etc/prometheus:/etc/prometheus # Simplified path
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - ops_overlay_network
      - default

  grafana:
    image: grafana/grafana
    ports:
      - 7070:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./etc/grafana/provisioning:/etc/grafana/provisioning # Simplified path
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafanasecret
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - ops_overlay_network
      - default

volumes:
  jenkins:
  prometheus_data:
  grafana_data:
networks:
  ops_overlay_network:
    external: true
  default:
